/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 bathroomSinkSquare.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bathroomSinkSquare.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_bathroomSinkSquare.geometry} material={materials.carpetWhite} />
      <mesh geometry={nodes.Mesh_bathroomSinkSquare_1.geometry} material={materials.metalDark} />
      <mesh geometry={nodes.Mesh_bathroomSinkSquare_2.geometry} material={materials.metalLight} />
    </group>
  )
}

useGLTF.preload('/bathroomSinkSquare.glb')
