/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 bathroomCabinet.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bathroomCabinet.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['bathroomCabinet(Clone)'].geometry} material={materials.wood}>
        <group position={[0.227, 0.027, -0.09]}>
          <mesh geometry={nodes.Mesh_door.geometry} material={materials.wood} />
          <mesh geometry={nodes.Mesh_door_1.geometry} material={materials.woodDark} />
          <mesh geometry={nodes.Mesh_door_2.geometry} material={materials.metal} />
        </group>
      </mesh>
    </group>
  )
}
