/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 bathroomCabinetDrawer.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bathroomCabinetDrawer.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_bathroomCabinetDrawer.geometry} material={materials.wood} />
      <mesh geometry={nodes.Mesh_bathroomCabinetDrawer_1.geometry} material={materials.carpetWhite} />
      <mesh geometry={nodes.Mesh_bathroomCabinetDrawer_2.geometry} material={materials.metalDark} />
      <mesh geometry={nodes.Mesh_bathroomCabinetDrawer_3.geometry} material={materials.metalLight} />
      <group position={[0.027, 0.085, -0.15]}>
        <mesh geometry={nodes.Mesh_drawerTop.geometry} material={materials.wood} />
        <mesh geometry={nodes.Mesh_drawerTop_1.geometry} material={materials.carpetWhite} />
        <mesh geometry={nodes.Mesh_drawerTop_2.geometry} material={materials.metalLight} />
      </group>
      <group position={[0.027, 0.238, -0.15]}>
        <mesh geometry={nodes.Mesh_drawerTop.geometry} material={materials.wood} />
        <mesh geometry={nodes.Mesh_drawerTop_1.geometry} material={materials.carpetWhite} />
        <mesh geometry={nodes.Mesh_drawerTop_2.geometry} material={materials.metalLight} />
      </group>
    </group>
  )
}

useGLTF.preload('/bathroomCabinetDrawer.glb')
