/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 bathroomMirror.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bathroomMirror.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_bathroomMirror.geometry} material={materials.wood} />
      <mesh geometry={nodes.Mesh_bathroomMirror_1.geometry} material={materials.metal} />
      <mesh geometry={nodes.Mesh_bathroomMirror_2.geometry} material={materials.glass} />
    </group>
  )
}

useGLTF.preload('/bathroomMirror.glb')
