/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 bear.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bear.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_bear.geometry} material={materials.fur} />
      <mesh geometry={nodes.Mesh_bear_1.geometry} material={materials.wood} />
      <mesh geometry={nodes.Mesh_bear_2.geometry} material={materials.metalDark} />
    </group>
  )
}

useGLTF.preload('/bear.glb')
