/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 bedBunk.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bedBunk.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_bedBunk.geometry} material={materials.wood} />
      <mesh geometry={nodes.Mesh_bedBunk_1.geometry} material={materials.carpetWhite} />
      <group position={[-0.375, 0.195, -0.827]} rotation={[0, -Math.PI / 2, 0]} scale={0.5}>
        <mesh geometry={nodes.Mesh_cover.geometry} material={materials.carpet} />
        <mesh geometry={nodes.Mesh_cover_1.geometry} material={materials.carpetWhite} />
      </group>
      <group position={[-0.375, 0.735, -0.827]} rotation={[0, -Math.PI / 2, 0]} scale={0.5}>
        <mesh geometry={nodes.Mesh_cover.geometry} material={materials.carpet} />
        <mesh geometry={nodes.Mesh_cover_1.geometry} material={materials.carpetWhite} />
      </group>
      <mesh geometry={nodes.pillowBottom.geometry} material={materials.carpetWhite} position={[0.118, 0.197, -1.066]} rotation={[0.126, -Math.PI / 2, 0]} scale={[0.5, 0.5, 0.85]} />
      <mesh geometry={nodes.pillowTop.geometry} material={materials.carpetWhite} position={[0.118, 0.737, -1.066]} rotation={[0.126, -Math.PI / 2, 0]} scale={[0.5, 0.5, 0.85]} />
    </group>
  )
}

useGLTF.preload('/bedBunk.glb')
