/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 bedSingle.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bedSingle.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_bedSingle.geometry} material={materials.carpetWhite} />
      <mesh geometry={nodes.Mesh_bedSingle_1.geometry} material={materials.wood} />
      <mesh geometry={nodes.Mesh_bedSingle_2.geometry} material={materials.metal} />
      <group position={[0.01, 0.215, -0.792]} rotation={[0, -Math.PI / 2, 0]} scale={0.5}>
        <mesh geometry={nodes.Mesh_cover.geometry} material={materials.carpet} />
        <mesh geometry={nodes.Mesh_cover_1.geometry} material={materials.carpetWhite} />
      </group>
      <mesh geometry={nodes.pillow.geometry} material={materials.carpetWhite} position={[0.503, 0.217, -1.031]} rotation={[0.126, -Math.PI / 2, 0]} scale={[0.5, 0.5, 0.85]} />
    </group>
  )
}

useGLTF.preload('/bedSingle.glb')
