/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 bookcaseClosedWide.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bookcaseClosedWide.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['bookcaseClosedWide(Clone)'].geometry} material={materials.wood} />
    </group>
  )
}

useGLTF.preload('/bookcaseClosedWide.glb')
