/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 books.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/books.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_books.geometry} material={materials.carpetDarker} />
      <mesh geometry={nodes.Mesh_books_1.geometry} material={materials.carpetWhite} />
      <mesh geometry={nodes.Mesh_books_2.geometry} material={materials.plant} />
      <mesh geometry={nodes.Mesh_books_3.geometry} material={materials.metal} />
    </group>
  )
}

useGLTF.preload('/books.glb')
