/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 cabinetBed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cabinetBed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['cabinetBed(Clone)'].geometry} material={materials.wood}>
        <group position={[0.025, 0.025, -0.02]}>
          <mesh geometry={nodes.Mesh_door.geometry} material={materials.wood} />
          <mesh geometry={nodes.Mesh_door_1.geometry} material={materials.metal} />
        </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('/cabinetBed.glb')
