/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 cabinetBedDrawer.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cabinetBedDrawer.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_cabinetBedDrawer.geometry} material={materials.wood} />
      <mesh geometry={nodes.Mesh_cabinetBedDrawer_1.geometry} material={materials._defaultMat} />
      <group position={[0.025, 0.055, -0.012]}>
        <mesh geometry={nodes.Mesh_door.geometry} material={materials.wood} />
        <mesh geometry={nodes.Mesh_door_1.geometry} material={materials.metal} />
      </group>
      <group position={[0.025, 0.168, -0.164]}>
        <mesh geometry={nodes.Mesh_drawer.geometry} material={materials.wood} />
        <mesh geometry={nodes.Mesh_drawer_1.geometry} material={materials.metal} />
      </group>
    </group>
  )
}

useGLTF.preload('/cabinetBedDrawer.glb')
