/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 cardboardBoxClosed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cardboardBoxClosed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_cardboardBoxClosed.geometry} material={materials.wood} />
      <mesh geometry={nodes.Mesh_cardboardBoxClosed_1.geometry} material={materials.woodDark} />
    </group>
  )
}

useGLTF.preload('/cardboardBoxClosed.glb')
