/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ceilingFan.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ceilingFan.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_ceilingFan.geometry} material={materials.metalLight} />
      <mesh geometry={nodes.Mesh_ceilingFan_1.geometry} material={materials.lamp} />
      <mesh geometry={nodes.Mesh_ceilingFan_2.geometry} material={materials.wood} />
    </group>
  )
}

useGLTF.preload('/ceilingFan.glb')
