/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 chairRounded.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chairRounded.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['chairRounded(Clone)'].geometry} material={materials.wood} />
    </group>
  )
}

useGLTF.preload('/chairRounded.glb')
