/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 chairDesk.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chairDesk.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['chairDesk(Clone)'].geometry} material={materials.metalMedium}>
        <group position={[0.167, 0.19, -0.16]}>
          <mesh geometry={nodes.Mesh_chair.geometry} material={materials.carpet} />
          <mesh geometry={nodes.Mesh_chair_1.geometry} material={materials.metalMedium} />
        </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('/chairDesk.glb')
