/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 coatRack.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/coatRack.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_coatRack.geometry} material={materials.metalMedium} />
      <mesh geometry={nodes.Mesh_coatRack_1.geometry} material={materials.wood} />
    </group>
  )
}

useGLTF.preload('/coatRack.glb')
