/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 computerScreen.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/computerScreen.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_computerScreen.geometry} material={materials.metalDark} />
      <mesh geometry={nodes.Mesh_computerScreen_1.geometry} material={materials.metal} />
    </group>
  )
}

useGLTF.preload('/computerScreen.glb')
