/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 computerKeyboard.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/computerKeyboard.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_computerKeyboard.geometry} material={materials.metalDark} />
      <mesh geometry={nodes.Mesh_computerKeyboard_1.geometry} material={materials.metalMedium} />
    </group>
  )
}

useGLTF.preload('/computerKeyboard.glb')
