/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 deskCorner.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/deskCorner.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['deskCorner(Clone)'].geometry} material={materials.wood}>
        <group position={[0.05, 0.274, -0.758]}>
          <mesh geometry={nodes.Mesh_drawer.geometry} material={materials.wood} />
          <mesh geometry={nodes.Mesh_drawer_1.geometry} material={materials.metal} />
        </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('/deskCorner.glb')
