/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 doorwayFront.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/doorwayFront.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['doorwayFront(Clone)'].geometry} material={materials.carpetWhite}>
        <group position={[0.028, 0, -0.045]}>
          <mesh geometry={nodes.Mesh_door.geometry} material={materials.metal} />
          <mesh geometry={nodes.Mesh_door_1.geometry} material={materials.metalDark} />
          <mesh geometry={nodes.Mesh_door_2.geometry} material={materials.glass} />
        </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('/doorwayFront.glb')
