/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 dryer.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/dryer.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_dryer.geometry} material={materials.metalLight} />
      <mesh geometry={nodes.Mesh_dryer_1.geometry} material={materials.metalMedium} />
      <mesh geometry={nodes.Mesh_dryer_2.geometry} material={materials.metalDark} />
      <mesh geometry={nodes.dryerDoor.geometry} material={materials.metalLight} position={[0.065, 0.226, 0]} />
    </group>
  )
}

useGLTF.preload('/dryer.glb')
