/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 hoodLarge.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/hoodLarge.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_hoodLarge.geometry} material={materials.metalDark} />
      <mesh geometry={nodes.Mesh_hoodLarge_1.geometry} material={materials._defaultMat} />
    </group>
  )
}

useGLTF.preload('/hoodLarge.glb')
