/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 hoodModern.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/hoodModern.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_hoodModern.geometry} material={materials.metalMedium} />
      <mesh geometry={nodes.Mesh_hoodModern_1.geometry} material={materials._defaultMat} />
    </group>
  )
}

useGLTF.preload('/hoodModern.glb')
