/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 kitchenCabinetCornerRound.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/kitchenCabinetCornerRound.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_kitchenCabinetCornerRound.geometry} material={materials.metal} />
      <mesh geometry={nodes.Mesh_kitchenCabinetCornerRound_1.geometry} material={materials.wood} />
    </group>
  )
}

useGLTF.preload('/kitchenCabinetCornerRound.glb')
