/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 kitchenFridgeSmall.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/kitchenFridgeSmall.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_kitchenFridgeSmall.geometry} material={materials.metalLight} />
      <mesh geometry={nodes.Mesh_kitchenFridgeSmall_1.geometry} material={materials.metalDark} />
      <group position={[0.027, 0.087, -0.025]}>
        <mesh geometry={nodes.Mesh_doorFridge.geometry} material={materials.metalLight} />
        <mesh geometry={nodes.Mesh_doorFridge_1.geometry} material={materials.glass} />
        <mesh geometry={nodes.Mesh_doorFridge_2.geometry} material={materials.metal} />
      </group>
    </group>
  )
}

useGLTF.preload('/kitchenFridgeSmall.glb')
