/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 kitchenStove.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/kitchenStove.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_kitchenStove.geometry} material={materials.metal} />
      <mesh geometry={nodes.Mesh_kitchenStove_1.geometry} material={materials.wood} />
      <mesh geometry={nodes.Mesh_kitchenStove_2.geometry} material={materials.metalDark} />
      <mesh geometry={nodes.Mesh_kitchenStove_3.geometry} material={materials.carpetWhite} />
      <group position={[0.027, 0.085, -0.03]}>
        <mesh geometry={nodes.Mesh_door.geometry} material={materials.metal} />
        <mesh geometry={nodes.Mesh_door_1.geometry} material={materials.glass} />
      </group>
    </group>
  )
}

useGLTF.preload('/kitchenStove.glb')
