/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 kitchenBarEnd.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/kitchenBarEnd.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_kitchenBarEnd.geometry} material={materials.wood} />
      <mesh geometry={nodes.Mesh_kitchenBarEnd_1.geometry} material={materials.metal} />
    </group>
  )
}

useGLTF.preload('/kitchenBarEnd.glb')
