/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 kitchenBar.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/kitchenBar.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_kitchenBar.geometry} material={materials.wood} />
      <mesh geometry={nodes.Mesh_kitchenBar_1.geometry} material={materials.metal} />
      <mesh geometry={nodes.Mesh_kitchenBar_2.geometry} material={materials.woodDark} />
    </group>
  )
}

useGLTF.preload('/kitchenBar.glb')
