/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 kitchenBlender.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/kitchenBlender.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_kitchenBlender.geometry} material={materials.metalMedium} />
      <mesh geometry={nodes.Mesh_kitchenBlender_1.geometry} material={materials.metal} />
      <mesh geometry={nodes.blenderCup.geometry} material={materials.glass} position={[0.016, 0.085, 0]} scale={0.79} />
      <mesh geometry={nodes.blenderTop.geometry} material={materials.metalMedium} position={[0.016, 0.212, 0]} scale={0.79} />
    </group>
  )
}

useGLTF.preload('/kitchenBlender.glb')
