/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 kitchenCabinetUpper.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/kitchenCabinetUpper.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['kitchenCabinetUpper(Clone)'].geometry} material={materials.wood}>
        <group position={[0.027, 0.027, -0.01]}>
          <mesh geometry={nodes.Mesh_door.geometry} material={materials.wood} />
          <mesh geometry={nodes.Mesh_door_1.geometry} material={materials.woodDark} />
          <mesh geometry={nodes.Mesh_door_2.geometry} material={materials.metal} />
        </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('/kitchenCabinetUpper.glb')
