/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 kitchenCabinet.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/kitchenCabinet.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_kitchenCabinet.geometry} material={materials.metal} />
      <mesh geometry={nodes.Mesh_kitchenCabinet_1.geometry} material={materials.wood} />
      <group position={[0.027, 0.085, -0.03]}>
        <mesh geometry={nodes.Mesh_door.geometry} material={materials.wood} />
        <mesh geometry={nodes.Mesh_door_1.geometry} material={materials.woodDark} />
        <mesh geometry={nodes.Mesh_door_2.geometry} material={materials.metal} />
      </group>
    </group>
  )
}

useGLTF.preload('/kitchenCabinet.glb')
