/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 kitchenMicrowave.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/kitchenMicrowave.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_kitchenMicrowave.geometry} material={materials.metalMedium} />
      <mesh geometry={nodes.Mesh_kitchenMicrowave_1.geometry} material={materials.carpetWhite} />
      <mesh geometry={nodes.Mesh_kitchenMicrowave_2.geometry} material={materials.metalDark} />
      <group position={[0.02, 0.02, 0]}>
        <mesh geometry={nodes.Mesh_Group_389.geometry} material={materials.carpetWhite} />
        <mesh geometry={nodes.Mesh_Group_389_1.geometry} material={materials.glass} />
        <mesh geometry={nodes.Mesh_Group_389_2.geometry} material={materials.metalMedium} />
      </group>
    </group>
  )
}

useGLTF.preload('/kitchenMicrowave.glb')
