/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 kitchenFridgeLarge.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/kitchenFridgeLarge.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['kitchenFridgeLarge(Clone)'].geometry} material={materials.metalLight}>
        <group position={[0.027, 0.49, 0.02]}>
          <mesh geometry={nodes.Mesh_doorLeft.geometry} material={materials.metalLight} />
          <mesh geometry={nodes.Mesh_doorLeft_1.geometry} material={materials.metalMedium} />
        </group>
        <group position={[0.493, 0.49, 0.02]}>
          <mesh geometry={nodes.Mesh_doorRight.geometry} material={materials.metalMedium} />
          <mesh geometry={nodes.Mesh_doorRight_1.geometry} material={materials.metalLight} />
        </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('/kitchenFridgeLarge.glb')
