/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 kitchenCabinetUpperDouble.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/kitchenCabinetUpperDouble.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['kitchenCabinetUpperDouble(Clone)'].geometry} material={materials.wood}>
        <group position={[0.027, 0.027, -0.01]}>
          <mesh geometry={nodes.Mesh_doorLeft.geometry} material={materials.woodDark} />
          <mesh geometry={nodes.Mesh_doorLeft_1.geometry} material={materials.wood} />
          <mesh geometry={nodes.Mesh_doorLeft_2.geometry} material={materials.metal} />
        </group>
        <group position={[0.403, 0.027, -0.01]}>
          <mesh geometry={nodes.Mesh_doorRight.geometry} material={materials.wood} />
          <mesh geometry={nodes.Mesh_doorRight_1.geometry} material={materials.metal} />
          <mesh geometry={nodes.Mesh_doorRight_2.geometry} material={materials.woodDark} />
        </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('/kitchenCabinetUpperDouble.glb')
