/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 kitchenStoveElectric.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/kitchenStoveElectric.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_kitchenStoveElectric.geometry} material={materials.metal} />
      <mesh geometry={nodes.Mesh_kitchenStoveElectric_1.geometry} material={materials.wood} />
      <mesh geometry={nodes.Mesh_kitchenStoveElectric_2.geometry} material={materials.metalDark} />
      <mesh geometry={nodes.Mesh_kitchenStoveElectric_3.geometry} material={materials.carpetWhite} />
      <mesh geometry={nodes.Mesh_kitchenStoveElectric_4.geometry} material={materials.glass} />
      <mesh geometry={nodes.Mesh_kitchenStoveElectric_5.geometry} material={materials.metalMedium} />
    </group>
  )
}

useGLTF.preload('/kitchenStoveElectric.glb')
