/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 kitchenFridgeBuiltIn.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/kitchenFridgeBuiltIn.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_kitchenFridgeBuiltIn.geometry} material={materials.wood} />
      <mesh geometry={nodes.Mesh_kitchenFridgeBuiltIn_1.geometry} material={materials.metalLight} />
      <mesh geometry={nodes.Mesh_kitchenFridgeBuiltIn_2.geometry} material={materials.woodDark} />
      <group position={[0.05, 0.651, -0.035]} scale={[0.875, 0.88, 1]}>
        <mesh geometry={nodes.Mesh_doorFreezer.geometry} material={materials.metalLight} />
        <mesh geometry={nodes.Mesh_doorFreezer_1.geometry} material={materials.wood} />
        <mesh geometry={nodes.Mesh_doorFreezer_2.geometry} material={materials.metal} />
      </group>
      <group position={[0.05, 0.109, -0.035]} scale={[0.875, 0.88, 1]}>
        <mesh geometry={nodes.Mesh_doorFridge.geometry} material={materials.wood} />
        <mesh geometry={nodes.Mesh_doorFridge_1.geometry} material={materials.metalLight} />
        <mesh geometry={nodes.Mesh_doorFridge_2.geometry} material={materials.metal} />
        <mesh geometry={nodes.Mesh_doorFridge_3.geometry} material={materials.glass} />
      </group>
    </group>
  )
}

useGLTF.preload('/kitchenFridgeBuiltIn.glb')
