/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 lampWall.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/lampWall.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.58}>
        <mesh geometry={nodes.Mesh_lampWall.geometry} material={materials.metal} />
        <mesh geometry={nodes.Mesh_lampWall_1.geometry} material={materials.lamp} />
      </group>
    </group>
  )
}

useGLTF.preload('/lampWall.glb')
