/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 lampRoundTable.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/lampRoundTable.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_lampRoundTable.geometry} material={materials.metal} />
      <mesh geometry={nodes.Mesh_lampRoundTable_1.geometry} material={materials.lamp} />
    </group>
  )
}

useGLTF.preload('/lampRoundTable.glb')
