/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 lampSquareTable.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/lampSquareTable.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_lampSquareTable.geometry} material={materials.lamp} />
      <mesh geometry={nodes.Mesh_lampSquareTable_1.geometry} material={materials.metal} />
    </group>
  )
}

useGLTF.preload('/lampSquareTable.glb')
