/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 laptop.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/laptop.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.44}>
        <mesh geometry={nodes.Mesh_laptop.geometry} material={materials.metalDark} />
        <mesh geometry={nodes.Mesh_laptop_1.geometry} material={materials.metal} />
        <mesh geometry={nodes.Mesh_laptop_2.geometry} material={materials.metalMedium} />
      </group>
    </group>
  )
}

useGLTF.preload('/laptop.glb')
