/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 loungeChair.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/loungeChair.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_loungeChair.geometry} material={materials.carpet} />
      <mesh geometry={nodes.Mesh_loungeChair_1.geometry} material={materials.wood} />
    </group>
  )
}

useGLTF.preload('/loungeChair.glb')
