/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 loungeChairRelax.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/loungeChairRelax.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_loungeChairRelax.geometry} material={materials.metal} />
      <mesh geometry={nodes.Mesh_loungeChairRelax_1.geometry} material={materials.carpet} />
      <mesh geometry={nodes.Mesh_loungeChairRelax_2.geometry} material={materials.wood} />
    </group>
  )
}

useGLTF.preload('/loungeChairRelax.glb')
