/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 loungeSofa.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/loungeSofa.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_loungeSofa.geometry} material={materials.carpet} />
      <mesh geometry={nodes.Mesh_loungeSofa_1.geometry} material={materials.wood} />
    </group>
  )
}

useGLTF.preload('/loungeSofa.glb')
