/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 loungeDesignChair.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/loungeDesignChair.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_loungeDesignChair.geometry} material={materials.carpetBlue} />
      <mesh geometry={nodes.Mesh_loungeDesignChair_1.geometry} material={materials.metal} />
    </group>
  )
}

useGLTF.preload('/loungeDesignChair.glb')
