/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 loungeDesignSofa.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/loungeDesignSofa.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_loungeDesignSofa.geometry} material={materials.carpetBlue} />
      <mesh geometry={nodes.Mesh_loungeDesignSofa_1.geometry} material={materials.metal} />
    </group>
  )
}

useGLTF.preload('/loungeDesignSofa.glb')
