/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 loungeDesignSofaCorner.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/loungeDesignSofaCorner.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_loungeDesignSofaCorner.geometry} material={materials.carpetBlue} />
      <mesh geometry={nodes.Mesh_loungeDesignSofaCorner_1.geometry} material={materials.metal} />
      <mesh geometry={nodes.Group.geometry} material={materials.metal} position={[0.942, 0.05, -1.282]} rotation={[0, 0, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('/loungeDesignSofaCorner.glb')
