/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 pottedPlant.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pottedPlant.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={2}>
        <mesh geometry={nodes.Mesh_pottedPlant.geometry} material={materials.wood} />
        <mesh geometry={nodes.Mesh_pottedPlant_1.geometry} material={materials.woodDark} />
        <mesh geometry={nodes.plant.geometry} material={materials.plant} position={[-0.053, 0.059, 0.06]} scale={0.5} />
      </group>
    </group>
  )
}

useGLTF.preload('/pottedPlant.glb')
