/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 radio.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/radio.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_radio.geometry} material={materials.metalMedium} />
      <mesh geometry={nodes.Mesh_radio_1.geometry} material={materials.wood} />
      <mesh geometry={nodes.Mesh_radio_2.geometry} material={materials.metal} />
    </group>
  )
}

useGLTF.preload('/radio.glb')
