/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 rugRounded.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/rugRounded.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_rugRounded.geometry} material={materials.carpetDarker} />
      <mesh geometry={nodes.Mesh_rugRounded_1.geometry} material={materials.carpet} />
    </group>
  )
}

useGLTF.preload('/rugRounded.glb')
