/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 rugSquare.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/rugSquare.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_rugSquare.geometry} material={materials.carpet} />
      <mesh geometry={nodes.Mesh_rugSquare_1.geometry} material={materials.carpetDarker} />
    </group>
  )
}

useGLTF.preload('/rugSquare.glb')
