/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 shower.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/shower.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, Math.PI / 2, 0]} scale={0.439}>
        <mesh geometry={nodes.Mesh_shower.geometry} material={materials.carpetWhite} />
        <mesh geometry={nodes.Mesh_shower_1.geometry} material={materials.metalDark} />
        <mesh geometry={nodes.Mesh_shower_2.geometry} material={materials.glass} />
        <mesh geometry={nodes.doorLeft.geometry} material={materials.glass} position={[0, 0.28, -0.64]} scale={2.278} />
        <group position={[0, 0.28, -0.061]} scale={2.278}>
          <mesh geometry={nodes.Mesh_doorRight.geometry} material={materials.glass} />
          <mesh geometry={nodes.Mesh_doorRight_1.geometry} material={materials.metal} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/shower.glb')
