/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 sideTableDrawers.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sideTableDrawers.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_sideTableDrawers.geometry} material={materials.wood} />
      <mesh geometry={nodes.Mesh_sideTableDrawers_1.geometry} material={materials._defaultMat} />
      <group position={[0.04, 0.274, -0.164]}>
        <mesh geometry={nodes.Mesh_drawer.geometry} material={materials.wood} />
        <mesh geometry={nodes.Mesh_drawer_1.geometry} material={materials.metal} />
      </group>
      <group position={[0.278, 0.274, -0.164]}>
        <mesh geometry={nodes.Mesh_drawer.geometry} material={materials.wood} />
        <mesh geometry={nodes.Mesh_drawer_1.geometry} material={materials.metal} />
      </group>
    </group>
  )
}

useGLTF.preload('/sideTableDrawers.glb')
