/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 sideTable.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sideTable.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_sideTable.geometry} material={materials.wood} />
      <mesh geometry={nodes.Mesh_sideTable_1.geometry} material={materials._defaultMat} />
    </group>
  )
}

useGLTF.preload('/sideTable.glb')
