/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 speakerSmall.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/speakerSmall.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_speakerSmall.geometry} material={materials.wood} />
      <mesh geometry={nodes.Mesh_speakerSmall_1.geometry} material={materials.metalMedium} />
    </group>
  )
}

useGLTF.preload('/speakerSmall.glb')
