/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 speaker.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/speaker.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_speaker.geometry} material={materials.wood} />
      <mesh geometry={nodes.Mesh_speaker_1.geometry} material={materials.metalMedium} />
    </group>
  )
}

useGLTF.preload('/speaker.glb')
