/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 stairsOpen.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/stairsOpen.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['stairsOpen(Clone)'].geometry} material={materials.woodDark}>
        <group position={[0.02, 0, -0.65]}>
          <mesh geometry={nodes.Mesh_Group_349.geometry} material={materials.metal} />
          <mesh geometry={nodes.Mesh_Group_349_1.geometry} material={materials.wood} />
        </group>
        <group position={[0.02, 0, -0.08]}>
          <mesh geometry={nodes.Mesh_Group_349.geometry} material={materials.metal} />
          <mesh geometry={nodes.Mesh_Group_349_1.geometry} material={materials.wood} />
        </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('/stairsOpen.glb')
