/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 stairsOpenSingle.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/stairsOpenSingle.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['stairsOpenSingle(Clone)'].geometry} material={materials.metal}>
        <mesh geometry={nodes.Group.geometry} material={materials.wood} position={[0.02, 0, -0.29]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/stairsOpenSingle.glb')
