/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 stairsCorner.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/stairsCorner.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_stairsCorner.geometry} material={materials.woodDark} />
      <mesh geometry={nodes.Mesh_stairsCorner_1.geometry} material={materials.wood} />
    </group>
  )
}

useGLTF.preload('/stairsCorner.glb')
