/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 tableCrossCloth.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tableCrossCloth.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.42}>
        <mesh geometry={nodes.Mesh_tableCrossCloth.geometry} material={materials.wood} />
        <mesh geometry={nodes.Mesh_tableCrossCloth_1.geometry} material={materials.carpet} />
      </group>
    </group>
  )
}

useGLTF.preload('/tableCrossCloth.glb')
