/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 tableCross.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tableCross.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['tableCross(Clone)'].geometry} material={materials.wood} scale={0.42} />
    </group>
  )
}

useGLTF.preload('/tableCross.glb')
