/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 tableCloth.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tableCloth.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_tableCloth.geometry} material={materials.wood} />
      <mesh geometry={nodes.Mesh_tableCloth_1.geometry} material={materials.carpet} />
    </group>
  )
}

useGLTF.preload('/tableCloth.glb')
