/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 televisionModern.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/televisionModern.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_televisionModern.geometry} material={materials.metalDark} />
      <mesh geometry={nodes.Mesh_televisionModern_1.geometry} material={materials.metal} />
    </group>
  )
}

useGLTF.preload('/televisionModern.glb')
