/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 televisionVintage.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/televisionVintage.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_televisionVintage.geometry} material={materials.metal} />
      <mesh geometry={nodes.Mesh_televisionVintage_1.geometry} material={materials.wood} />
      <mesh geometry={nodes.Mesh_televisionVintage_2.geometry} material={materials.metalMedium} />
      <mesh geometry={nodes.Mesh_televisionVintage_3.geometry} material={materials.metalDark} />
    </group>
  )
}

useGLTF.preload('/televisionVintage.glb')
