/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 toaster.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/toaster.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_toaster.geometry} material={materials.metalMedium} />
      <mesh geometry={nodes.Mesh_toaster_1.geometry} material={materials.metal} />
    </group>
  )
}

useGLTF.preload('/toaster.glb')
