/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 toilet.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/toilet.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, -Math.PI / 2, 0]} scale={0.475}>
        <mesh geometry={nodes.Mesh_toilet.geometry} material={materials.carpetWhite} />
        <mesh geometry={nodes.Mesh_toilet_1.geometry} material={materials.metalLight} />
        <mesh geometry={nodes.Mesh_toilet_2.geometry} material={materials.metalDark} />
        <mesh geometry={nodes.cover.geometry} material={materials._defaultMat} position={[0.255, 0.479, -0.329]} scale={2.105} />
      </group>
    </group>
  )
}

useGLTF.preload('/toilet.glb')
