/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 wallWindowSlide.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/wallWindowSlide.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_wallWindowSlide.geometry} material={materials.wood} />
      <mesh geometry={nodes.Mesh_wallWindowSlide_1.geometry} material={materials.metalDark} />
      <mesh geometry={nodes.Mesh_wallWindowSlide_2.geometry} material={materials._defaultMat} />
      <group position={[0.313, 0.393, -0.015]}>
        <mesh geometry={nodes.Mesh_windowBottom.geometry} material={materials.glass} />
        <mesh geometry={nodes.Mesh_windowBottom_1.geometry} material={materials.wood} />
      </group>
      <group position={[0.313, 0.725, 0.01]}>
        <mesh geometry={nodes.Mesh_windowTop.geometry} material={materials.glass} />
        <mesh geometry={nodes.Mesh_windowTop_1.geometry} material={materials.wood} />
      </group>
    </group>
  )
}

useGLTF.preload('/wallWindowSlide.glb')
