/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 wallWindow.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/wallWindow.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_wallWindow.geometry} material={materials.wood} />
      <mesh geometry={nodes.Mesh_wallWindow_1.geometry} material={materials.metalDark} />
      <mesh geometry={nodes.Mesh_wallWindow_2.geometry} material={materials._defaultMat} />
      <group position={[0.313, 0.393, -0.003]}>
        <mesh geometry={nodes.Mesh_window.geometry} material={materials.glass} />
        <mesh geometry={nodes.Mesh_window_1.geometry} material={materials.wood} />
      </group>
    </group>
  )
}

useGLTF.preload('/wallWindow.glb')
