/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 wall.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/wall.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_wall.geometry} material={materials.wood} />
      <mesh geometry={nodes.Mesh_wall_1.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.Mesh_wall_2.geometry} material={materials.metalDark} />
    </group>
  )
}

useGLTF.preload('/wall.glb')
