/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 wallDoorwayWide.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/wallDoorwayWide.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_wallDoorwayWide.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.Mesh_wallDoorwayWide_1.geometry} material={materials.wood} />
      <mesh geometry={nodes.Mesh_wallDoorwayWide_2.geometry} material={materials.metalDark} />
    </group>
  )
}

useGLTF.preload('/wallDoorwayWide.glb')
