/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 washer.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/washer.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_washer.geometry} material={materials.metalLight} />
      <mesh geometry={nodes.Mesh_washer_1.geometry} material={materials.metalMedium} />
      <mesh geometry={nodes.Mesh_washer_2.geometry} material={materials.metalDark} />
      <group position={[0.065, 0.226, 0.01]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Mesh_washerDoor.geometry} material={materials.metal} />
        <mesh geometry={nodes.Mesh_washerDoor_1.geometry} material={materials.glass} />
        <mesh geometry={nodes.Mesh_washerDoor_2.geometry} material={materials._defaultMat} />
      </group>
    </group>
  )
}

useGLTF.preload('/washer.glb')
