/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 car.gltf
Author: Urizel (https://sketchfab.com/urizel)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/bottled-car-cd38a415db8a4607ab9dd3cc67d27462
Title: Bottled car
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Car(props) {
  const { nodes, materials } = useGLTF("/car.gltf")
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={[16,16,16]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.BOTTLE_OUTSIDE} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.LIGHT} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.BOTTOM} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.BOTTLE_WOOD} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.BOTTLE_INSIDE} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.BASEMETAL} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.NAMEPLATE} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.GLASS_N_CHROME} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.GLASS_N_CHROME} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.INTERIOR} />
      </group>
    </group>
  )
}

useGLTF.preload('/car.gltf')
